KOGITO-7849: Patch PR for KOGITO-7422 with doc improvements in serverless logic web tools guides
kiegroup/kogito-docs pull request #187
Opened 2022-09-02 13:36 UTC by hmanwani-rh

**JIRA:** https://issues.redhat.com/browse/KOGITO-7849

**Description:** Patch PR for KOGITO-7422 with doc improvements in serverless logic web tools guides

https://github.com/kiegroup/kogito-docs/pull/160

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributions doc](https://github.com/kiegroup/kogito-docs/blob/main/CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] The nav.adoc file has a link to this guide in the proper category
- [ ] The index.adoc file has a card to this guide in the proper category, with a meaningful description

<details>
<summary>
How to setup automatic cherry-pick to another branch ?
</summary>

The cherry-pick action allows to setup automatic cherry-pick from `main` to a specific branch.

To allow it, you will need to add the corresponding label with pattern: `backport-{RELEASE_BRANCH}`.  
For example, if a backport to branch `1.26.x` is needed, then the label should be `backport-1.26.x`.

Once the PR is merged, the action will retrieve the commit and cherry-pick it to the desired branch.

*NOTE: You can still add label after the merge and it should still be cherry-picked.*
</details>

2022-09-02 13:41 UTC, hmanwani-rh commented
@thiagoelg Please review the changes made in this PR and share your comments.

2022-09-02 16:16 UTC, thiagoelg requested changes
@hmanwani-rh Thanks for this PR, looks great!

I've pointed out some things that I would change for clarification, let me know what you think.

2022-09-02 16:16 UTC, thiagoelg commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-github-integration.adoc
> +. Select the *Use Quarkus Accelerator* to create a repository with a base Quarkus project and move the workspace files to `src/main/resources` folder.
This step is optional.

```suggestion
. Optionally, select the *Use Quarkus Accelerator* to create a repository with a base Quarkus project and move the workspace files to `src/main/resources` folder.
```

2022-09-02 16:16 UTC, thiagoelg commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-redhat-application-services-integration.adoc
> +You can skip this step if you already have a Service Registry.
```suggestion
You can skip this step if you already have a Service Registry instance.
```

2022-09-07 08:50 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc
> +* *Upload OpenAPI spec to Service Registry*: After a workflow is deployed, an OpenAPI specification is available in the deployed service. When you check this option, the {serverless_logic_web_tools_n
Done, changed the sentence as follows:

When you check this option, the {serverless_logic_web_tools_name} fetches the OpenAPI specification, and when ready, the OpenAPI specification is uploaded to your configured service registry.

2022-09-07 08:50 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc
> +* *Attach KafkaSource to the deployment*: You must check this option, if your workflow contains an Apache Kafka event dependency. To use this option, you need to configure your service account and st
Done

2022-09-07 08:52 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc
> +A pop-up appears displaying *Your deployment has been successfully started and will be available shortly. Please do not close this browser tab until the operation is completed.* message and a *OpenSh
Done

2022-09-07 08:54 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc
> +* Deployed project must be deployed using the *Deploy as a project* option as unchecked, as the deployment page is only available using the pre-built image container. If the option *Deploy as a proje
Done

2022-09-07 08:56 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-enable-kogito-swf-visualization.adoc
> +The Kogito Serverless Workflow Visualization feature in {serverless_logic_web_tools_name} enables you to preview your workflow diagrams alongside the editor. This document describes how you can enabl
Replaced it with "a rendering engine"
since the engine currently is new, sooner it will not be :)

2022-09-07 08:58 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-github-integration.adoc
> +This document describes how you can configure the integration and sychronize your {context} projects.
Done

2022-09-07 08:59 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-github-integration.adoc
> +After set your GitHub token, you can synchronize your workspaces with remote repositories.
Done

2022-09-07 09:00 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-github-integration.adoc
> +. Create or open a workspace in GitHub.
Done

2022-09-07 09:01 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-github-integration.adoc
> +. Select the *Use Quarkus Accelerator* to create a repository with a base Quarkus project and move the workspace files to `src/main/resources` folder.
Done

2022-09-07 09:09 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-redhat-application-services-integration.adoc
> +You can skip this step if you already have a Service Registry.
Done

2022-09-07 09:10 UTC, hmanwani-rh commented
> @hmanwani-rh Thanks for this PR, looks great!
> 
> I've pointed out some things that I would change for clarification, let me know what you think.

@thiagoelg Thanks for reviewing the changes. I've made the changes as suggested. Please take a look and let me know if we can merge this PR.

2022-09-12 13:08 UTC, thiagoelg approved these changes
Looks good!
Thanks @hmanwani-rh

2022-09-12 14:22 UTC, merged