Update dev ui start workflow page
kiegroup/kogito-docs pull request #226
Opened 2022-10-11 11:18 UTC by AjayJagan

**Description:**
This PR updates the Serverless workflow quarkus Dev-UI guide to incorporate the latest changes.
 - includes the new screenshots
 - Adds the information about the start workflow based on the form page.

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributions doc](https://github.com/kiegroup/kogito-docs/blob/main/CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] The nav.adoc file has a link to this guide in the proper category
- [ ] The index.adoc file has a card to this guide in the proper category, with a meaningful description

<details>
<summary>
How to setup automatic cherry-pick to another branch ?
</summary>

The cherry-pick action allows to setup automatic cherry-pick from `main` to a specific branch.

To allow it, you will need to add the corresponding label with pattern: `backport-{RELEASE_BRANCH}`.  
For example, if a backport to branch `1.26.x` is needed, then the label should be `backport-1.26.x`.

Once the PR is merged, the action will retrieve the commit and cherry-pick it to the desired branch.

*NOTE: You can still add label after the merge and it should still be cherry-picked.*
</details>

2022-10-11 11:53 UTC, ricardozanini approved these changes

2022-10-11 11:59 UTC, radtriste commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +The Start New Workflow page is used start a workflow instance through a cloud event or a custom form depending on the workflow configuration. To navigate to the *Start New Workflow* page, click on th
```suggestion
The Start New Workflow page is used to start a workflow instance through a cloud event or a custom form, depending on the workflow configuration. To navigate to the *Start New Workflow* page, click on the play button in the *Actions* column of the workflow definitions table.
```

2022-10-11 11:59 UTC, radtriste commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +If there is no json schema for the workflow, then the workflow will be started by triggering a cloud event.
```suggestion
*If there is no json schema for the workflow*, then the workflow will be started by triggering a cloud event.
```

2022-10-11 11:59 UTC, radtriste commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +If the workflow has a json schema configured in the `dataInputSchema` property, then a form is displayed in-order to start a new workflow instance. You can fill-in the required form details and click
```suggestion
*If there is a json schema for the workflow* configured in the `dataInputSchema` property, then a form is displayed in-order to start a new workflow instance. You can fill-in the required form details and click on the *Start* button to trigger the workflow.
```

2022-10-14 18:29 UTC, paulovmr requested changes

2022-10-14 18:29 UTC, paulovmr commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +*If there is a json schema for the workflow* configured in the `dataInputSchema` property, then a form is displayed in-order to start a new workflow instance. You can fill-in the required form detail
```suggestion
*If there is a json schema for the workflow* configured in the `dataInputSchema` property, then a form is displayed in order to start a new workflow instance. You can fill in the required form details and click on the *Start* button to trigger the workflow.
```

2022-10-17 18:23 UTC, paulovmr approved these changes

2022-10-18 07:22 UTC, pefernan approved these changes

2022-10-18 13:22 UTC, ricardozanini commented
@kaldesai can you take a look, please?

2022-10-18 14:08 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +The Start New Workflow page is used to start a workflow instance through a cloud event or a custom form, depending on the workflow configuration. To navigate to the *Start New Workflow* page, click o
```suggestion
The *Start New Workflow* page is used to start a workflow instance through a cloud event or a custom form, depending on the workflow configuration. To navigate to the *Start New Workflow* page, click the play button in the *Actions* column of the workflow definitions table.
```

2022-10-18 14:09 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +*If there is no json schema for the workflow*, then the workflow will be started by triggering a cloud event.
```suggestion
*If there is no JSON schema for the workflow, then the workflow is started by triggering a cloud event.
```

2022-10-18 14:11 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +To trigger a cloud event, you can use the *Cloud Event Type* and *Cloud Event Data* input fields to set the type of a cloud event and event payload in JSON format respectively, and click the *Start*
```suggestion
To trigger a cloud event, you can use the *Cloud Event Type* and *Cloud Event Data* input fields to set the type of a cloud event and event payload in JSON format respectively and click the *Start* button to start a workflow. The *Reset* button on the page resets the values entered in the given fields.
```

2022-10-18 14:12 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +.Starting a workflow using cloud event
```suggestion
.Starting a workflow using a cloud event
```

2022-10-18 14:13 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +*If there is a json schema for the workflow* configured in the `dataInputSchema` property, then a form is displayed in order to start a new workflow instance. You can fill in the required form detail
```suggestion
*If there is a JSON schema for the workflow configured in the `dataInputSchema` property, then a form is displayed to start a new workflow instance. You can fill in the required form details and click the *Start* button to trigger the workflow.
```

2022-10-18 14:15 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
> +.Starting a workflow using form
```suggestion
.Starting a workflow using the form
```

2022-10-18 14:15 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
>  You can also use the *Business key* text box to define a custom business key value to the workflow instance. If the *Business Key* field is blank, then an auto-generated business key is defined to th
```suggestion
You can also use the *Business key* text box to define a custom business key value to the workflow instance. If the *Business Key* field is blank, then an auto-generated business key is defined for the workflow instance.
```

2022-10-18 14:17 UTC, kaldesai approved these changes
@AjayJagan Added my minor suggestion. Please reach out to me if you have any queries related to my suggestions. Thank you!

2022-10-18 14:32 UTC, AjayJagan commented
@kaldesai  thanks for the review. I have updated the PR with your suggestions. Let me know if I need to change anything else . :)

2022-10-18 17:34 UTC, kaldesai commented
> @kaldesai thanks for the review. I have updated the PR with your suggestions. Let me know if I need to change anything else . :)

@AjayJagan I think that's it from my side. :) Thank you!

2022-11-10 15:31 UTC, AjayJagan commented
> It seems this is ready to be merged? And probably we want to backport to 1.30.x branch so it will be included in DP3? @AjayJagan

@krisv  yes I have resolved all the comments and is ready to be merged and it should be backported to 1.30.x .

2022-11-10 16:13 UTC, MarianMacik approved these changes

2022-11-14 13:27 UTC, merged