Update swf diagram docs
kiegroup/kogito-docs pull request #242
Opened 2022-10-21 08:14 UTC by AjayJagan

**Description:**
 This PR updates the Serverless workflow diagram documentation  to incorporate the new changes added by 
 https://github.com/kiegroup/kogito-apps/pull/1451
 which replaces the SVG preview with a read-only editor.

 https://github.com/kiegroup/kogito-apps/pull/1451

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributions doc](https://github.com/kiegroup/kogito-docs/blob/main/CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] The nav.adoc file has a link to this guide in the proper category
- [ ] The index.adoc file has a card to this guide in the proper category, with a meaningful description

<details>
<summary>
How to setup automatic cherry-pick to another branch ?
</summary>

The cherry-pick action allows to setup automatic cherry-pick from `main` to a specific branch.

To allow it, you will need to add the corresponding label with pattern: `backport-{RELEASE_BRANCH}`.  
For example, if a backport to branch `1.26.x` is needed, then the label should be `backport-1.26.x`.

Once the PR is merged, the action will retrieve the commit and cherry-pick it to the desired branch.

*NOTE: You can still add label after the merge and it should still be cherry-picked.*
</details>

2022-10-21 09:53 UTC, AjayJagan commented
to be merged after :
https://github.com/kiegroup/kogito-apps/pull/1451

2022-10-21 13:36 UTC, pefernan requested changes

2022-10-21 13:36 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
> +
@AjayJagan I'd mention here that stunner only works for `*.sw.json` files, for `yaml` it will show always mermaid

2022-10-21 13:40 UTC, pefernan approved these changes

2022-10-21 14:28 UTC, ricardozanini approved these changes

2022-10-25 14:39 UTC, paulovmr approved these changes

2022-10-31 05:57 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-overview.adoc
> +. Enter the following command to add `kogito-addons-quarkus-source-files` extension that provides the source code to generate the Serverless Workflow diagram in the consoles:
```suggestion
. Enter the following command to add the `kogito-addons-quarkus-source-files` extension that provides the source code to generate the Serverless Workflow diagram in the consoles:
```

2022-10-31 05:58 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
> +By default the Stunner diagram is displayed. To toggle between the two diagrams you can use the `kogito.swf.stunner.enabled`(defaulted to true) environment variable in your application.properties.
```suggestion
By default, the Stunner diagram is displayed. To toggle between the two diagrams you can use the `kogito.swf.stunner.enabled`(defaulted to true) environment variable in your application properties.
```

2022-10-31 05:59 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
> +For yaml based workflow files, the mermaid diagram is displayed instead of the the stunner diagram.
```suggestion
For yaml-based workflow files, the mermaid diagram is displayed instead of the stunner diagram.
```

2022-10-31 06:03 UTC, kaldesai approved these changes

2022-11-07 06:01 UTC, AjayJagan commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
> +By default the Stunner diagram is displayed. To toggle between the two diagrams you can use the `kogito.swf.stunner.enabled`(defaulted to true) environment variable in your application.properties.
Hi @MarianMacik, I have added a note in the documentation : https://github.com/kiegroup/kogito-docs/pull/242/files#diff-78c38540914bd385590018ec1c9889afb2a3c6a669d70493768cf0451540e084R70

2022-11-07 10:23 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
> +By default the Stunner diagram is displayed. To toggle between the two diagrams you can use the `kogito.swf.stunner.enabled`(defaulted to true) environment variable in your application.properties.
@MarianMacik is it still the case. I think that's something will be addressed in stunner in the shorter term and then we could get rid of mermaid.

2022-11-07 16:10 UTC, MarianMacik commented on serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
> +By default the Stunner diagram is displayed. To toggle between the two diagrams you can use the `kogito.swf.stunner.enabled`(defaulted to true) environment variable in your application.properties.
Sorry guys, I have overlooked the note.

2022-11-14 13:28 UTC, ricardozanini commented
@AjayJagan do we need to backport this to 1.30.x?

2022-11-14 13:29 UTC, AjayJagan commented
> @AjayJagan do we need to backport this to 1.30.x?

yes I think we should backport it.

2022-11-14 18:48 UTC, merged