Remove unnecessary quarkus-container-jib extension
kiegroup/kogito-docs pull request #283
Opened 2023-01-20 12:30 UTC by ricardozanini

There's no apparent reason to add this dependency to the project. Users might use the Cloud Guides to build/generate the application image instead of adding the extension in the Getting Started.

2023-01-20 12:31 UTC, spolti approved these changes

2023-01-20 12:34 UTC, radtriste requested changes
Also update the logs in https://kiegroup.github.io/kogito-docs/serverlessworkflow/latest/getting-started/create-your-first-workflow-service.html#proc-running-application
just remove the JIB log line :)

2023-01-20 12:34 UTC, radtriste commented on serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
> -    -x=quarkus-container-image-jib \
Please also remove its mention in the explanation just after

2023-01-20 13:50 UTC, radtriste approved these changes

2023-01-23 00:22 UTC, cristianonicolai approved these changes

2023-01-23 13:52 UTC, ricardozanini commented
@kaldesai anything to point out? If not, feel free to merge it.

2023-01-23 13:53 UTC, kaldesai approved these changes

2023-01-23 13:54 UTC, kaldesai commented
> @kaldesai anything to point out? If not, feel free to merge it.

@ricardozanini Nothing from my side. Approved the PR! Sure, I will merge it.

2023-01-23 13:55 UTC, merged