[KOGITO-8908] Documenting sysout arguments and log level
kiegroup/kogito-docs pull request #321
Opened 2023-03-23 17:45 UTC by fjtirado

**JIRA:**

https://issues.redhat.com/browse/KOGITO-8908

2023-03-23 18:22 UTC, hbelmiro requested changes

2023-03-23 18:22 UTC, hbelmiro commented on serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
> +`message` argument can be an jq expression or a jq string using interpolation, as in the example above
```suggestion
`message` argument can be a jq expression or a jq string using interpolation, as in the example above
```

2023-03-23 20:09 UTC, hbelmiro approved these changes

2023-03-28 13:10 UTC, radtriste commented
@kaldesai can you have a final look ?

2023-04-03 17:34 UTC, MarianMacik approved these changes

2023-04-11 10:53 UTC, fjtirado commented
@kaldesai Can you please take a look?

2023-04-11 11:34 UTC, kaldesai commented on serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
> +The string after the : is optional and is used to indicate the log level. Possible values are TRACE, DEBUG, INFO, WARN and ERROR. If not present, INFO is assumed.
```suggestion
The string after the `:` is optional and is used to indicate the log level.  The possible values are TRACE, DEBUG, INFO, WARN, and ERROR. If not present, INFO is considered by default. 
```

2023-04-11 11:35 UTC, kaldesai approved these changes
@fjtirado, Just a small suggestion. Otherwise, it looks good to me. Thank you!

2023-04-11 13:20 UTC, merged