KOGITO-7271 Add swf docs
kiegroup/kogito-docs pull request #33
Opened 2022-06-24 04:33 UTC by AjayJagan

**JIRA:**: https://issues.redhat.com/browse/KOGITO-7271
Please make sure that your PR meets the following requirements:

- [ x ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ x ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ x ] The nav.adoc file has a link to this guide in the proper category

2022-06-24 12:52 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
> +The Chrome Extension for Serverless Workflow Editor allows you to view and edit Serverless Workflow files in github.
```suggestion
The Chrome Extension for Serverless Workflow Editor allows you to view and edit Serverless Workflow files in GitHub.
```

2022-06-24 12:54 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
> +* You can visit chrome web store with https://chrome.google.com/webstore/detail/serverless-workflow-edito/ijamhkegfogkfnmfnfkjdiadomlphfej[Chrome extension for serverless workflow editor] and click o
maybe use the link patter as we are doing on other guides?
common link on antora.yaml and links only used here, below the header.

2022-06-24 12:54 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
> +* You can download and extract the chrome_extension_serverless_workflow_editor_VERSION.zip file from the https://github.com/kiegroup/kie-tools/releases[kie-tools] releases page in GitHub, and then in
```suggestion
* You can download and extract the 'chrome_extension_serverless_workflow_editor_VERSION.zip' file from the https://github.com/kiegroup/kie-tools/releases[kie-tools] releases page in GitHub, and then in the upper-right corner in Chrome, go to *Customize and control* → *Settings* → *Extensions* → *Load unpacked* and open the extracted dist folder.
```

2022-06-24 12:55 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
> +.Serverless Workflow file opened in github
```suggestion
.Serverless Workflow file opened in GitHub
```

2022-06-24 12:55 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
> +You can switch to *full-screen* mode to switch to a full screen editor. You can hide the editor and view the source code on github using the *See as source* button.
```suggestion
You can switch to *full-screen* mode to switch to a full screen editor. You can hide the editor and view the source code on GitHub using the *See as source* button.
```

2022-06-24 12:57 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
> +NOTE: The editor currently performs validation using JSON schema to the structure of workflow file and not the values in it and context based auto-complete works only with JSON and not with YAML.
@ederign is there plans to support auto complete with yaml file?

2022-06-24 12:59 UTC, spolti reviewed
imho, this file swf-editor-chrome-extension-release-page.png can be removed.

2022-06-24 13:00 UTC, spolti reviewed
maybe this file too [swf-editor-edit-mode-commit.png](https://github.com/kiegroup/kogito-docs/pull/33/files#diff-d770521270d4abd0be2f7f656f9c1305517fdfc48a8d9713a7d3b6ccc30e3cf3)

2022-06-24 13:01 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* You can visit https://marketplace.visualstudio.com/items?itemName=redhat.vscode-extension-serverless-workflow-editor[Red Hat Serverless Workflow Editor] and follow the instructions or use the *exte
link.

2022-06-24 13:01 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* You can download the _vscode_extension_serverless_workflow_editor_VERSION.vsix_ https://github.com/kiegroup/kie-tools/releases[kie-tools] and install it in vscode using the *Install from VSIX* opti
same

2022-06-24 13:02 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +```
```suggestion
----
```

2022-06-24 13:03 UTC, spolti commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* https://marketplace.visualstudio.com/items?itemName=redhat.vscode-redhat-account[Redhat authentication extension]
same

2022-06-24 13:31 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
> += Serverless Workflow Editor
```suggestion
= Kogito Serverless Workflow Editor
```

2022-06-24 13:32 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
> +NOTE: The editor currently performs validation using JSON schema to the structure of workflow file and not the values in it and context based auto-complete works only with JSON and not with YAML.
```suggestion
[NOTE]
====
The editor currently performs validation using JSON schema to the structure of the workflow file and not the values in it and context-based auto-complete works only with JSON and not with YAML.
====
```

2022-06-24 13:32 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> += VScode Extension for Serverless Workflow Editor
```suggestion
= VScode Extension for the Kogito Serverless Workflow Editor
```

2022-06-24 13:33 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* Visual Studio Code version 1.46.0 and above.
Please add this version to serverlessworkflow/antora.yaml file.

2022-06-24 13:33 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +.Serverless Workflow VScode Extension
```suggestion
.Kogito Serverless Workflow VScode Extension
```

2022-06-24 13:35 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/nav.adoc
> +*** xref:tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc[Chrome extension for Serverless Workflow Editor]
```suggestion
*** xref:tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc[Chrome extension for Kogito Serverless Workflow Editor]
```

2022-06-24 13:35 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/nav.adoc
> +*** xref:tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc[VScode extension for Serverless Workflow Editor]
```suggestion
*** xref:tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc[VScode extension for Kogito Serverless Workflow Editor]
```

2022-06-24 14:21 UTC, AjayJagan commented
> maybe this file too [swf-editor-edit-mode-commit.png](https://github.com/kiegroup/kogito-docs/pull/33/files#diff-d770521270d4abd0be2f7f656f9c1305517fdfc48a8d9713a7d3b6ccc30e3cf3)

Hey @spolti , thanks for the review. Here should I remove the content+image or keep the content and remove the image.

2022-06-24 14:22 UTC, AjayJagan commented
@ricardozanini , thanks for the review. I have changed `Serverless Workflow Editor` to `Kogito Serverless Workflow Editor`. Let me know if you need any changes :)

2022-06-24 14:27 UTC, spolti commented
> > maybe this file too [swf-editor-edit-mode-commit.png](https://github.com/kiegroup/kogito-docs/pull/33/files#diff-d770521270d4abd0be2f7f656f9c1305517fdfc48a8d9713a7d3b6ccc30e3cf3)
> 
> Hey @spolti , thanks for the review. Here should I remove the content+image or keep the content and remove the image.

the image only, but, it is just a personal suggestion :)

2022-06-24 19:49 UTC, ricardozanini reviewed
Here's the follow-up, @AjayJagan! Great work, many thanks!

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
> +Once you are done with the installation, create a Serverless Workflow file(ending with *.sw.json* or *.sw.yaml*) and push it to GitHub or visit any GitHub page with a similar type of file and click o
```suggestion
Once you are done with the installation, create a Serverless Workflow file (ending with *.sw.json* or *.sw.yaml*) and push it to GitHub or visit any GitHub page with a similar type of file and click on it to open the editor.
```

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
> +The Serverless Workflow Editor is a tool to manipulate the content of serverless workflow files and simultaneously view the workflow diagram.
```suggestion
The Kogito Serverless Workflow Editor is a tool to manipulate the content of CNCF Serverless Workflow Specification files and simultaneously view the workflow diagram.
```
Please add the link to the specification: https://serverlessworkflow.io/

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +The VScode extension for the Kogito Serverless Workflow Editor allows you to view and edit serverless workflow files in your local projects.
```suggestion
The VScode extension for the Kogito Serverless Workflow Editor allows you to view and edit CNCF Serverless Workflow Specification files in your local projects.
```

Same here, please add the link to the spec: https://serverlessworkflow.io/

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +== Installing VScode Extension
```suggestion
== Installing the VScode Extension
```

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +== Working with VScode Extension
```suggestion
== Working with the VScode Extension
```

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +The extension can use openAPI spec files stored locally in the 'specs folder'(<<Kogito Serverless Workflow Editor Setttings,check the settings section>>) or in remote Service Registries to provide ad
Can you please add a link to the OpenAPI Spec? There's a variable introduced by this PR: #18

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +NOTE: After selecting one of the options in the auto-complete dialog, the openAPI spec file will be downloaded into the 'specs' folder(<<Kogito Serverless Workflow Editor Setttings,Configured in the
```suggestion
[NOTE]
====
After selecting one of the options in the auto-complete dialog, the openAPI spec file will be downloaded into the 'specs' folder(<<Kogito Serverless Workflow Editor Setttings,Configured in the settings>>). The saved file follows the format of _REGISTRY-NAME_OPERATION-NAME_VERSION_.
====
```

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +Click on the *Add funtion*... button to create a new Function Definition object.
```suggestion
Click on the *Add function*... button to create a new Function Definition object.
```

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +=== Connecting the extension to Apicurio Serivce Registries
```suggestion
=== Connecting the extension to Apicurio Service Registries
```

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +The extension has the capability to connect to a remote Service Registry inorder to enhance the auto-complete capabilities of the Workflow's Function Definitions section.
```suggestion
The extension has the capability to connect to a remote Service Registry in order to enhance the auto-complete capabilities of the Workflow's Function Definitions section.
```

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +NOTE: The *Group* is not mandatory for Apicurio but is mandatory of the extension to work. Please make sure to enter a value there.
```suggestion
[NOTE] 
====
The *Group* is not mandatory for Apicurio but is mandatory for the extension to work. Please make sure to enter a value there.
====
```

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +save the settings and you have successfully connected to the remote Apicurio Service Registry.
```suggestion
Save the settings and you have successfully connected to the remote Apicurio Service Registry.
```

2022-06-24 19:49 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +NOTE: Currently validation is performed only for JSON files. The validation is based out of JSON schema and it checks only the structure of the json and not the content.
```suggestion
[NOTE]
====
Currently validation is performed only for JSON files. The validation is based on JSON schema, and it checks only the structure of the JSON and not the content.
====
```

2022-06-25 17:01 UTC, AjayJagan commented
> Here's the follow-up, @AjayJagan! Great work, many thanks!

Thanks again @ricardozanini :). Resolved them now :+1:

2022-06-27 14:51 UTC, ricardozanini approved these changes
LGTM! A few minor comments only. Great work! Many thanks!

2022-06-27 14:51 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
> +The Kogito Serverless Workflow Editor is a tool to manipulate the content of CNCF Serverless Workflow Specification files and simultaneously view the workflow diagram. The editor has two parts, a cod
Please add the link to "CNCF Serverless Workflow Specification". Every time we mention a project at the beginning of the guide, we should add a link back to it.

2022-06-27 14:51 UTC, ricardozanini commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +The VScode extension for the Kogito Serverless Workflow Editor allows you to view and edit CNCF Serverless Workflow Specification files in your local projects.
Same here about the link to the spec.

2022-06-27 14:58 UTC, pefernan requested changes
Added some suggestions regarding the extensions settings and other small bits.

I think we could rearrange the `Service Registry Settings` and `Connecting the extension to Apicurio Service Registries` in a single section.

2022-06-27 14:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* *Serverless Workflow: Configure Service Registries*: Opens the configuration for the Service Registries.
```suggestion
* *Serverless Workflow: Configure Service Registries*: Opens the configuration for the Service Registries in the Extension Settings screen.
```

2022-06-27 14:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* *Service Registries*: Provides a link to access the _settings.json_, to configure the Serivce Registries.
```suggestion
* *Service Registries*: Gives access to the Service Registries configuration in the _settings.json_ file.
```

2022-06-27 14:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* *Should Reference Service Registry Functions With Urls*: Provides a check box to toggle between downloading the openAPI file or use the url of the function in Service Registry.
```suggestion
* *Should Reference Service Registry Functions With Urls*: when autocompleting functions from OpenAPI files in the Service Registry, this setting specifies if the Function operation should use the URL to the OpenAPI file or use a local path (file will be downloaded to the *Specs Storage Path*).
```

2022-06-27 14:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* *Svg Filename Template*: Provides a text box to edit the filename template to be used when generating SVG files.
```suggestion
* *Svg Filename Template*: Sets the filename template to be used when generating the diagram SVG file. Defaults to '{fileName}.svg'.
```

2022-06-27 14:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* *Svg File Path*: Provides a text box to edit the path to generate SVG files.
```suggestion
* *Svg File Path*: Sets he path to store the diagram SVG. Defaults to the same edited Serverless Workflow directory.
```

2022-06-27 14:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +The extension can use link:{open_api_spec_url}[openAPI spec] files stored locally in the 'specs folder'(<<Kogito Serverless Workflow Editor Setttings,check the settings section>>) or in remote Servic
```suggestion
The extension can use link:{open_api_spec_url}[OpenAPI spec] files stored locally in the 'specs folder' (<<Kogito Serverless Workflow Editor Setttings,check the settings section>>) or in remote Service Registries to provide advanced auto-complete features for *Function Definitions*.
```

2022-06-27 14:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +The extension is able to parse the openAPI spec files and provide the list of Function Definitions in the auto-complete dialog.
```suggestion
The extension is able to parse the OpenAPI spec files and provide the list of Function Definitions in the auto-complete dialog.
```

2022-06-27 14:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +====
I think this Note and the following part (Refresh service registries...) could be moved to the Service Registries section

2022-06-27 14:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +=== Service Registry settings
I think we may have to change a bit the contents of this section, we could probably consolidate it with the `Connecting the extension to Apicurio Service Registries`

2022-06-28 06:51 UTC, akumar074 approved these changes
LGTM! Thanks @AjayJagan

2022-06-28 14:27 UTC, pefernan approved these changes
+1 Thank you @AjayJagan great job!

2022-06-28 15:57 UTC, pefernan commented on serverlessworkflow/modules/ROOT/nav.adoc
> +*** xref:tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc[VScode extension for Kogito Serverless Workflow Editor]
```suggestion
*** xref:tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc[VS Code extension for Kogito Serverless Workflow Editor]
```

@AjayJagan we missed this!

2022-06-28 15:58 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* You can download the 'vscode_extension_serverless_workflow_editor_VERSION.vsix' link:{kie_tools_releases_page_url}[kie-tools] and install it in vscode using the *Install from VSIX* option in the ex
```suggestion
* You can download the 'vscode_extension_serverless_workflow_editor_VERSION.vsix' link:{kie_tools_releases_page_url}[kie-tools] and install it in VS Code using the *Install from VSIX* option in the extensions menu.
```

2022-06-28 16:28 UTC, AjayJagan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +* You can download the 'vscode_extension_serverless_workflow_editor_VERSION.vsix' link:{kie_tools_releases_page_url}[kie-tools] and install it in vscode using the *Install from VSIX* option in the ex
fixed

2022-06-28 16:28 UTC, AjayJagan commented on serverlessworkflow/modules/ROOT/nav.adoc
> +*** xref:tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc[VScode extension for Kogito Serverless Workflow Editor]
my bad! fixed

2022-06-28 17:18 UTC, ricardozanini commented
Congrats! Moving to docs review cc @hmanwani-rh

2022-06-29 15:46 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +          "authUrl": {
@AjayJagan a last minute comment, could you please get rid of the `authUrl`& `clientId` here?

2022-06-29 15:47 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +            "enum": ["none", "red-hat-account", "oidc"],
@AjayJagan a last minute change, we'll get rid of `oidc` for now, could you please get rid of this?
```suggestion
            "enum": ["none", "red-hat-account"],
```

2022-06-29 15:47 UTC, pefernan commented on serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
> +        "allOf": [
@AjayJagan and also this "allOf": [...] array?

2022-06-30 17:08 UTC, hmanwani-rh approved these changes
@AjayJagan I've added tweaks to the content. Please take a look and let me know if the applied changes look good. 

Doc preview: https://deploy-preview-33--tangerine-crostata-04a6bf.netlify.app/serverlessworkflow/main/tooling/serverless-workflow-editor/swf-editor-overview.html

2022-06-30 17:38 UTC, merged