KOGITO-7248: Patch PR for KOGITO-6996 with doc improvements in parallelism guide
kiegroup/kogito-docs pull request #82
Opened 2022-07-26 10:11 UTC by hmanwani-rh

**JIRA:** https://issues.redhat.com/browse/KOGITO-7248

**Description:** Patch PR for KOGITO-6996 with doc improvements in parallelism guide

https://github.com/kiegroup/kogito-docs/pull/77

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributions doc](https://github.com/kiegroup/kogito-docs/blob/main/CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] The nav.adoc file has a link to this guide in the proper category
- [ ] The index.adoc file has a card to this guide in the proper category, with a meaningful description

2022-07-26 10:13 UTC, hmanwani-rh commented
@hbelmiro Please review the changes applied in this PR and let me know if the changes look good.

2022-07-26 14:02 UTC, hbelmiro requested changes
Thanks for your improvements @hmanwani-rh.
I left a few comments.

2022-07-27 11:37 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
> +Serverless Workflow serializes the execution of parallel tasks. Therefore, the word "parallel" does not indicate simultaneous execution, but it means that there is no logical dependency between the e
Done, added Kogito and removed Serverless Workflow.

2022-07-27 11:38 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
> +You can start the Serverless Workflow application in developer mode by using the following command:
Done

2022-07-27 11:38 UTC, hmanwani-rh commented on serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
> +This means that the parallel state is completed when all the branches are completed.
Done

2022-07-27 11:40 UTC, hmanwani-rh commented
> Thanks for your improvements @hmanwani-rh. I left a few comments.

@hbelmiro Thanks for reviewing the changes and sharing your comments. I've incorporated the changes as suggested.

2022-07-27 12:34 UTC, hbelmiro approved these changes

2022-07-27 12:35 UTC, merged